# Generated by Django 4.1 on 2022-08-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='third_party',
            name='type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_name',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='status',
        ),
        migrations.AlterField(
            model_name='reciept',
            name='reciept_type',
            field=models.CharField(choices=[('withdraw', 'withdraw'), ('deposit', 'deposit')], max_length=20, null=True),
        ),
    ]
