# Generated by Django 4.0.6 on 2022-07-30 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('account_type', models.CharField(max_length=20)),
                ('account_balance', models.IntegerField()),
                ('account_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_currency', to='wallet.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_customer', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(max_length=20)),
                ('transaction_amount', models.IntegerField()),
                ('transaction_name', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(max_length=20)),
                ('transaction_charge', models.IntegerField()),
                ('date_and_time', models.DateTimeField()),
                ('destination_account', models.IntegerField()),
                ('receipt', models.CharField(max_length=20)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Third_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Third_party_account', to='wallet.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Third_party_currency', to='wallet.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=20)),
                ('customer_id', models.IntegerField()),
                ('points', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('third_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reward_third_party', to='wallet.third_party')),
            ],
        ),
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept_type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=20)),
                ('balance', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('receipt_file', models.FileField(upload_to='')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reciept_transaction', to='wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_description', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('date_and_time', models.DateTimeField()),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Notifications_recipient', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.IntegerField()),
                ('date_and_time', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('loan_status', models.CharField(max_length=20)),
                ('interest_rate', models.IntegerField()),
                ('payment_due_date', models.DateTimeField()),
                ('loan_balance', models.IntegerField()),
                ('guarantor', models.CharField(max_length=20)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loan_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('card_name', models.CharField(max_length=20)),
                ('date_issued', models.DateTimeField()),
                ('card_type', models.CharField(max_length=20)),
                ('expiry_date', models.IntegerField()),
                ('security_code', models.IntegerField()),
                ('issuer', models.CharField(max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_account', to='wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Account_wallet', to='wallet.wallet'),
        ),
    ]
