# Generated by Django 4.1 on 2022-08-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_customer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
